### PR TITLE
added district for larger cities

### PR DESCRIPTION
**Pull request by 5uper**
added district for larger cities

### CODE REVIEW

**Comment by maleeb** [comment]
+1

**Comment by 5uper** [comment]
@sebastianbaar please update it here too
https://www.npmjs.com/package/cordova-plugin-nativegeocoder

**Comment by sebastianbaar** [comment]
@5uper done!

**Comment by 5uper** [comment]
@Hamza-Rhaman 
update to the latest ionic-native v.3.5.0
https://github.com/driftyco/ionic-native/releases/tag/v3.5.0

**Pull request merged**
